### ISSUE TITLE
GLIBC versions not found

### ISSUE THREAD

**Issue by wizard-28** [angelofallars/treefetch#1]
I installed the `treefetch` binary in my system from the Releases. When I try to run `treefetch` I get this error:
```
treefetch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by treefetch)
treefetch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by treefetch)
```

I'm on Pop!_OS 20.04 (based on Ubuntu 20.04)

**Comment by wizard-28** [comment]
Running `apt show libc6 | grep -i version` shows `2.31-0ubuntu9.2` (or version `2.31`), can you make `treefetch` compatible with this version of GLIBC too?

**Comment by angelofallars** [comment]
Hi @wizard-28! Does this binary file work? It is linked against the MUSL Libc.
https://github.com/angelofallars/treefetch/releases/download/v1.2.1/treefetch

**Comment by wizard-28** [comment]
The new release worked thanks!
